services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: toor
        POSTGRES_DB: restaurant-manager
    networks:
      - restaurant-manager-network
    volumes:
      - restaurant-manager-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: restaurant-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant-manager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
    networks:
      - restaurant-manager-network

volumes:
  restaurant-manager-data:

networks:
  restaurant-manager-network:
